In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers).text

In [3]:
soup = BeautifulSoup(webpage, "lxml")

#print(soup.prettify())

In [4]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
HDB Financial Services
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [5]:
company = soup.find_all('div', class_='companyCardWrapper')
len(company)

20

In [7]:
company_name = []
rating = []
reviews = []
highlyRatedFor = []
jobs = []
salary = []


for i in company:
    company_name.append(i.find('h2').text.strip())
    rating.append(i.find('div', class_='rating_text').text.strip())
    reviews.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())
    highlyRatedFor.append(i.find('span', class_='companyCardWrapper__ratingValues').text.strip())
    jobs.append(i.find_all('span', class_='companyCardWrapper__ActionCount')[3].text.strip())
    salary.append(i.find_all('span', class_='companyCardWrapper__ActionCount')[1].text.strip())
# print(len(company_name))
# print(len(rating))

print(company_name)
print(rating)
print(reviews)
print(highlyRatedFor)
print(jobs)
print(salary)

['TCS', 'Accenture', 'Wipro', 'Cognizant', 'Capgemini', 'HDFC Bank', 'Infosys', 'HCLTech', 'ICICI Bank', 'Tech Mahindra', 'Genpact', 'TP', 'Jio', 'Axis Bank', 'Concentrix Corporation', 'Amazon', 'Reliance Retail', 'iEnergizer', 'LTIMindtree', 'HDB Financial Services']
['3.3', '3.7', '3.6', '3.7', '3.6', '3.8', '3.5', '3.4', '4.0', '3.3', '3.6', '3.9', '4.4', '3.6', '3.6', '3.9', '3.9', '4.6', '3.6', '3.9']
['(1.2L)', '(75k)', '(66.2k)', '(62.5k)', '(54.6k)', '(53.6k)', '(49.7k)', '(46.9k)', '(46.6k)', '(44.1k)', '(43.3k)', '(39.5k)', '(34k)', '(34k)', '(32.8k)', '(32.3k)', '(27.7k)', '(27.4k)', '(26.9k)', '(26.2k)']
['Job Security', 'Promotions, Salary, Work Satisfaction', 'Promotions, Salary, Work Satisfaction', 'Promotions, Salary, Work Satisfaction', 'Work Life Balance, Job Security', 'Job Security, Skill Development', 'Job Security', 'Promotions, Salary, Work Satisfaction', 'Job Security, Promotions, Skill Development', 'Promotions, Salary, Work Satisfaction', 'Job Security', 'Work Life Balance, Job Security, Skill Development', 'Job Security, Skill Development, Company Culture', 'Promotions, Work Satisfaction, Company Culture', 'Job Security', 'Company Culture, Work Life Balance, Salary', 'Job Security, Skill Development, Work Life Balance', 'Company Culture, Work Life Balance, Work Satisfaction', 'Promotions, Salary, Work Satisfaction', 'Promotions, Salary']
['4.7k', '23.6k', '4.2k', '932', '2.1k', '248', '3k', '235', '11', '685', '587', '1.8k', '--', '218', '18', '82', '100', '73', '541', '4']
['10.3L', '7.1L', '4.9L', '6.1L', '4.9L', '1.5L', '5.3L', '3.9L', '1.6L', '2.9L', '2.4L', '1L', '62.1k', '1L', '1.3L', '1.6L', '76.6k', '25k', '2L', '49.9k']

In [8]:
company[0].find_all('span', class_='companyCardWrapper__ActionCount')[3].text.strip()

'4.7k'

In [9]:
d = {'company': company_name, 
     'rating': rating,
     'reviews': reviews,
     'highlyRatedFor': highlyRatedFor,
     'jobs': jobs,
     'salary': salary
    }
df = pd.DataFrame(d)
df

,company,rating,reviews,highlyRatedFor,jobs,salary
0,TCS,3.3,(1.2L),Job Security,4.7k,10.3L
1,Accenture,3.7,(75k),"Promotions, Salary, Work Satisfaction",23.6k,7.1L
2,Wipro,3.6,(66.2k),"Promotions, Salary, Work Satisfaction",4.2k,4.9L
3,Cognizant,3.7,(62.5k),"Promotions, Salary, Work Satisfaction",932,6.1L
4,Capgemini,3.6,(54.6k),"Work Life Balance, Job Security",2.1k,4.9L
5,HDFC Bank,3.8,(53.6k),"Job Security, Skill Development",248,1.5L
6,Infosys,3.5,(49.7k),Job Security,3k,5.3L
7,HCLTech,3.4,(46.9k),"Promotions, Salary, Work Satisfaction",235,3.9L
8,ICICI Bank,4.0,(46.6k),"Job Security, Promotions, Skill Development",11,1.6L
9,Tech Mahindra,3.3,(44.1k),"Promotions, Salary, Work Satisfaction",685,2.9L
10,Genpact,3.6,(43.3k),Job Security,587,2.4L
11,TP,3.9,(39.5k),"Work Life Balance, Job Security, Skill Develop...",1.8k,1L
12,Jio,4.4,(34k),"Job Security, Skill Development, Company Culture",--,62.1k
13,Axis Bank,3.6,(34k),"Promotions, Work Satisfaction, Company Culture",218,1L
14,Concentrix Corporation,3.6,(32.8k),Job Security,18,1.3L
15,Amazon,3.9,(32.3k),"Company Culture, Work Life Balance, Salary",82,1.6L
16,Reliance Retail,3.9,(27.7k),"Job Security, Skill Development, Work Life Bal...",100,76.6k
17,iEnergizer,4.6,(27.4k),"Company Culture, Work Life Balance, Work Satis...",73,25k
18,LTIMindtree,3.6,(26.9k),"Promotions, Salary, Work Satisfaction",541,2L
19,HDB Financial Services,3.9,(26.2k),"Promotions, Salary",4,49.9k

In [10]:
final_df = pd.DataFrame()

for j in range(1,201):
    url = 'https://www.ambitionbox.com/list-of-companies?page={}'.format(j)

    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
    }
    webpage = requests.get(url, headers=headers).text

    soup = BeautifulSoup(webpage, "lxml")
    company = soup.find_all('div', class_='companyCardWrapper')

    company_name = []
    rating = []
    reviews = []
    highlyRatedFor = []
    jobs = []
    salary = []


    for i in company:
        company_name.append(i.find('h2').text.strip())

        try:
            rating.append(i.find('div', class_='rating_text').text.strip())
        except:
            rating.append(np.nan)


        try:
            reviews.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())
        except:
            reviews.append(np.nan)


        try:
            highlyRatedFor.append(i.find('span', class_='companyCardWrapper__ratingValues').text.strip())
        except:
            highlyRatedFor.append(np.nan)


        try:
            jobs.append(i.find_all('span', class_='companyCardWrapper__ActionCount')[3].text.strip())
        except:
            jobs.append(np.nan)


        try:
            salary.append(i.find_all('span', class_='companyCardWrapper__ActionCount')[1].text.strip())
        except:
            salary.append(np.nan)
    
    d = {'company': company_name, 
     'rating': rating,
     'reviews': reviews,
     'highlyRatedFor': highlyRatedFor,
     'jobs': jobs,
     'salary': salary
    }
    df = pd.DataFrame(d)

    final_df = pd.concat([final_df, df], ignore_index=True)


final_df

,company,rating,reviews,highlyRatedFor,jobs,salary
0,TCS,3.3,(1.2L),Job Security,4.7k,10.3L
1,Accenture,3.7,(75k),"Promotions, Salary, Work Satisfaction",23.6k,7.1L
2,Wipro,3.6,(66.2k),"Promotions, Salary, Work Satisfaction",4.2k,4.9L
3,Cognizant,3.7,(62.5k),"Promotions, Salary, Work Satisfaction",932,6.1L
4,Capgemini,3.6,(54.6k),"Work Life Balance, Job Security",2.1k,4.9L
...,...,...,...,...,...,...
2815,CEVA Logistics,3.8,(403),"Promotions, Company Culture, Salary",--,1.5k
2816,S. M. Auto Engineering,3.4,(402),"Promotions, Company Culture, Salary",2,1.5k
2817,Sunstone,3.7,(402),Work Life Balance,57,1.7k
2818,Karamtara Engineering Limited,3.6,(402),"Company Culture, Promotions, Work Life Balance",12,1.6k
2819,Tirumala Milk Products,4.2,(402),"Company Culture, Work Life Balance, Skill Deve...",9,1.1k

In [11]:
final_df.isna().sum()

company           0
rating            2
reviews           2
highlyRatedFor    2
jobs              0
salary            0
dtype: int64

In [12]:
final_df.to_csv('company.csv')